### ISSUE TITLE
Add support for .timer units

### ISSUE THREAD

**Issue by kdave** [kdave/btrfsmaintenance#29]
Currently, the scripts are started by the cron daemon. There's some user interst to use the systemd .timer units.

The scripts are independent of the executing daemon. What's needed:
* enhance configuration of sysconfig file to point to the timer-defined period (eg. value `timer` instead of daily/..., so we don't have to sync 2 files), the periods are defined in the .timer files
* document the changes
* enhance installers to select which type of executing daemon is wanted

**Comment by sten0** [comment]
Yay!  I've been planning to officially package btrfsmaintenance for Debian for a while, and this is something I'm very much interested in, and would like to help out with in late May or June.  I would also like to see:

* ConditionACPower=yes in the timer units, because maintenance operations will needlessly deplete battery life on laptops, and servers that are on emergency UPS power should probably defer as well
* Combined with anachron-like behaviour so that these tasks will run when AC power is restored
* Support for running these tasks in one-shot mode.  I believe this is useful for the following situation: a company usually scrubs on the 1st of the month, but an immanent product launch will ensure that the servers will be very busy for at least the first week of the next month.  I'm not sure if systemd supports deferring scheduled tasks, but it definitely has a mechanism for checking if a job has run in the last 'now -30 days'.  One-shot mode means the scrub can be manually triggered at a time before the surge in traffic to best assure quality of service.  The unit for check on the 1st of next month exits with "scrub unneeded".  The unit for check on the 1st of next next month finds that a scrub has now been completed in ~37 days or so and executes as expected.

1. Because Debian supports both sysvinit and systemd I'm going to also have to ask for some help on how it should be packaged.  My best guess is that there will be a btrfsmaintenance virtual package satisfied by either btrfsmaintenance-sysvinit or btrfsmaintenance-systemd.

2. Another of my concerns is the different syntaxes I've seen in how different distributions write their systemd timer units.  At this point I'm unable to say whether these differences are a matter of style/convention or actually affect functionality, but I'm willing to support the Debian expectations.  Worse case scenario would be maintaining a patch branch and rebasing off official upstream btrfsmaintenance and manually resolving the conflicts.

**Comment by madmartin** [comment]
Hi,
I added btrfsmaintenance to gentoo and had a PR for systemd timers.
Maybe someone wants to get in contact with the author for a well designed implementation here. 
The PR with my comments is here: https://github.com/gentoo/gentoo/pull/5160

**Comment by comio** [comment]
Dear all,

I issued a PR #34 in order to add systemd timers support. Any comment is welcome.

ciao

luigi

**Comment by comio** [comment]
See PR #35 with the updated patches.

ciao

luigi

**Comment by kdave** [comment]
The pull request #36 implements the core part of the timers.

**Comment by kdave** [comment]
The points from discussion moved to a separate issue, the timers are considered done and will be in the next release.
