### ISSUE TITLE
Add support for custom MAILTO

### ISSUE THREAD

**Issue by quirxmode** [kdave/btrfsmaintenance#32]
Output of the jobs is mailed to root@localhost per default. It would be nice if one could specify an email address where the output of the jobs is to be sent.

**Comment by ian-kelling** [comment]
A quick glance at debian shows this is not a standard feature of system cronjobs, and I think it would be best to follow precedent in this case. The proper way to do this is to redirect mail to root@localhost to somewhere else through various supported standard means, such as /etc/aliases .forward file, sieve rules, etc.

**Comment by kdave** [comment]
Thanks for the insights, I'm not against adding a mail reporting capability. Currently there's at `BTRFS_LOG_OUTPUT` with various output targets, which is quite simple to configure. Adding a mail target would require to add an external template, so the output has at least timestamp, hostname and descriptive subject. And maybe this would also require multiple target specification, because the logs should be also stored on the machine itself.

**Comment by kdave** [comment]
An alternate way for this feature is available, there's not enough interest to implemet that inside this project. Closing.

**Comment by MartinX3** [comment]
> An alternate way for this feature is available, there's not enough interest to implemet that inside this project. Closing.

Which alternate way?
I'm glad if I find a ways to report btrfs raid, checksum, etc errors to an email via s-nail (mail), msmtp or msmtp-mta (sendmail alias).
